apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nydus-snapshotter
  namespace: nydus-system
spec:
  template:
    spec:
      volumes:
        - name: containerd-conf
          hostPath:
            path: /var/lib/rancher/rke2/agent/etc/containerd/
